### ISSUE TITLE
Does not build on Ubuntu 14.04

### ISSUE THREAD

**Issue by purxiz** [nstafie/dca-rs#5] opened 2016-12-06 00:16 UTC
Running cargo buid returns error: Could not compile `syntex_syntax`
Verbose results here: http://pastebin.com/sf2m2hAT
When I tried to reproduce the issue in Fedora 24, it failed at a different point:
Results: http://pastebin.com/JUHSN2C9

First error below:
root@datboi3:~/dca/dca-rs-0.1.0# cargo build
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.1
   Compiling vec_map v0.4.0
   Compiling pkg-config v0.3.8
   Compiling winapi v0.2.5
   Compiling term v0.2.14
   Compiling opus-sys v0.2.0 (file:///root/dca/dca-rs-0.1.0/lib/rust-opus/opus-sys)
   Compiling unicode-xid v0.0.3
   Compiling strsim v0.4.0
   Compiling ansi_term v0.7.2
   Compiling bitflags v0.3.3
   Compiling byteorder v0.5.0
   Compiling num v0.1.31
   Compiling libc v0.2.8
   Compiling log v0.3.5
   Compiling rustc-serialize v0.3.18
   Compiling syntex_syntax v0.29.1
error: Could not compile `syntex_syntax`.

To learn more, run the command again with --verbose.

**Comment by nstafie** [comment] 2016-12-10 14:36
Sorry for the late response, I've been busy this week. Have you managed to compile it? 

I have no idea as to why `syntex_syntax` is causing your build to fail, but in terms of your build failing due to `#[derive_Debug]` errors, that's because the latest Rust compiler no longer accepts custom_derive, which it previously did when dca-rs was first written.

I've been working on a complete overhaul of dca-rs, and progress has been slow, but steady. Until then, it looks like this version won't compile on the latest Rust.

Until then, perhaps you could try the [pre-built binaries](https://github.com/nstafie/dca-rs/releases)? Those should work as intended.

**Comment by nstafie** [comment] 2017-02-26 00:18
I take it you've found a solution? If so I'll just close this. Feel free to open a new issue if it breaks again.

**Closed by nstafie** 2017-02-26 00:18 UTC
